apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-users
  template:
    metadata:
      labels:
        app: auth-users
    spec:
      containers:
        - name: auth-users
          image: checkm8-auth_users:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-users
spec:
  type: ClusterIP
  selector:
    app: auth-users
  ports:
    - port: 8080
      targetPort: 8080
